[env]
_.path = ["{{config_root}}/node_modules/.bin", "{{config_root}}/bin"]
_.file = { path = ".env.local", redact = true }

[hooks]
postinstall = ["npx corepack enable", "yarn"]

[tools]
go = "latest"
just = "latest"
node = "lts"
ruby = "latest"
rust = "latest"
zig = "latest"
