/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const camelCase: typeof import('es-toolkit').camelCase
  const capitalize: typeof import('es-toolkit').capitalize
  const compact: typeof import('es-toolkit').compact
  const constantCase: typeof import('es-toolkit').constantCase
  const groupBy: typeof import('es-toolkit').groupBy
  const identity: typeof import('es-toolkit').identity
  const isObject: typeof import('es-toolkit/compat').isObject
  const keyBy: typeof import('es-toolkit').keyBy
  const keys: typeof import('es-toolkit/compat').keys
  const mapKeys: typeof import('es-toolkit').mapKeys
  const mapValues: typeof import('es-toolkit').mapValues
  const maxBy: typeof import('es-toolkit').maxBy
  const minBy: typeof import('es-toolkit').minBy
  const partition: typeof import('es-toolkit').partition
  const pascalCase: typeof import('es-toolkit').pascalCase
  const pickBy: typeof import('es-toolkit').pickBy
  const range: typeof import('es-toolkit').range
  const template: typeof import('es-toolkit/compat').template
  const values: typeof import('es-toolkit/compat').values
}
